FROM mhart/alpine-node:slim-12 as node-src

FROM golang:1.15-alpine

# RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories \
#         && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
#         && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
#         && echo "http://dl-cdn.alpinelinux.org/alpine/v3.12/main" >> /etc/apk/repositories \
#         && apk add --no-cache nodejs curl git perl bash binutils make gcc

RUN apk add --no-cache nodejs make git bash npm perl

COPY --from=node-src /usr/bin/node /usr/bin/node
